#!/usr/bin/env bash
# Install and configure HAproxy

# Update Packages
apt-get -y update
apt-get -y upgrade

# Add Haproxy PPA
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.5
app-get -y update

# Install Haproxy
apt-get -y install haproxy=2.5.\*

# Configure Haproxy
config="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 102998-web-01 18.233.64.140:80  check
    server 102998-web-02 54.157.186.85:80 check
"
cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo $config >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
