#!/usr/bin/env bash
# Installs HAProxy version 2.6(LTS) with the following configurations:
# Distributes requests using a round-robin algorithm.

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 102998-web-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 102998-web-02 52.90.15.29:80 check\n\tserver 102998-web-01 3.90.85.114:80  check" /etc/haproxy/haproxy.cfg
# sudo service haproxy start
sudo /etc/init.d/haproxy  start
